# Generated by Django 4.1.7 on 2023-04-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchase", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasesummary",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="supplier.supplier"
            ),
        ),
    ]
